### ISSUE TITLE
Support Python 3.10 builds

### ISSUE THREAD

**Issue by mrakitin** [conda-forge/pdfstream-feedstock#11]
### Comment:

There is an explicit restriction of Python <3.10:
https://github.com/conda-forge/pdfstream-feedstock/blob/124afdfe20a5072930af5f4504dfc3cec1a00f9d/recipe/meta.yaml#L23

@st3107, is it intentional? Does the package need more work? I am trying to build a conda environment based on Python 3.10, but encountered this issue. Thanks!

**Comment by st3107** [comment]
I pinned it because one closed source dependency diffpy.pdfgetx only
supports python <3.10. Since it is closed source, it is not on conda, and I
have to pin the version of pdfstream to let conda know that it won't work
in python >=3.10. I will update the diffpy.pdfgetx and then unpin the
python for pdfstream.

**Comment by mrakitin** [comment]
Closed via #12.
